name: Build on Tag

on:
  push:
    tags: [ 'v*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: 17 }
      - uses: gradle/actions/setup-gradle@v4

      - name: Assemble Debug
        if: contains(github.ref_name, '-alpha') || contains(github.ref_name, '-debug')
        run: ./gradlew assembleDebug

      - name: Assemble Release
        if: '! (contains(github.ref_name, ''-alpha'') || contains(github.ref_name, ''-debug''))'
        run: ./gradlew assembleRelease

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: |
            app/build/outputs/apk/debug/*.apk
            app/build/outputs/apk/release/*.apk
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}